#!/bin/bash
echo "Automated Performance Evaluation"
echo "--------------------------------"
echo "To evaluate the STATIC baseline:"
echo "  1. In Terminal 1: osken-manager src/controller/static_router.py"
echo "  2. In Terminal 2: sudo python3 tests/evaluate_performance.py static"
echo ""
echo "To evaluate the DYNAMIC controller:"
echo "  1. In Terminal 1: osken-manager src/controller/dynamic_router.py"
echo "  2. In Terminal 2: sudo python3 tests/evaluate_performance.py dynamic"
echo ""
echo "After running both, compare the latency_ms and status in performance_metrics.csv."
